import Image from 'next/image';
import Link from 'next/link';
import { morvelio } from '@/content/projects';
import { WIKI, ICON, entries, entryPath, getEntry } from '@/content/morvelio/wiki/registry';
import './Wiki.css';

export function MorvelioPage(){
 const atlas=getEntry('world.erdavia')!;
 return <div className="mwiki mw-landing"><section className="mw-hero" aria-labelledby="morvelio-title"><div><p className="mw-eyebrow">Blajeen Labs · RPG de ação solo</p><h1 id="morvelio-title">Morvelio</h1><p className="text-[clamp(22px,3vw,35px)] leading-tight tracking-tight">Em Velidor o mal já venceu,<br/>e só os aventureiros se recusam a aceitar.</p><p className="mw-lead mt-6">Uma jornada por vilas, minas, máquinas e salões de um castelo tomado pelas sombras. Escolha sua classe, prepare seu equipamento e descubra o que um contrato pode esconder.</p><div className="mw-landing-links"><Link className="mw-button" href={WIKI}>Explorar a wiki →</Link><Link className="mw-button secondary" href={entryPath(atlas)}>Conhecer Erdávia</Link></div><p className="mw-muted text-xs">Em desenvolvimento · protótipo jogável interno · lançamento público ainda sem ficha de loja confirmada.</p></div><Image src={ICON} alt="Morvelio no alto da montanha, observando Velidor com o brilho do Orbe na bolsa" width={512} height={512} priority sizes="(max-width:760px) 85vw, 512px"/></section>
 <section className="mw-section"><p className="mw-eyebrow">Uma aventura com raízes</p><h2>O reino tem uma história.<br/>Seu aventureiro tem um caminho.</h2><p className="mw-lead">Morvelio combina combate em visão superior, exploração e progressão em uma campanha individual. O universo nasce também nas páginas de um livro: famílias, ofícios, relíquias e escolhas dão significado a cada lugar.</p><div className="mw-cols">{[
 ['Sete classes, sua identidade','Cavaleiro, Bárbaro, Ladina, Maga, Patrulheira, Druida e Engenheiro. Kits e armas distintos; a direção atual permite que você escolha o nome e a origem do aventureiro.','classes'],
 ['Caminhos que levam às profundezas','A Cova Alva, a Grande Roda e as dez alas do Castelo têm objetivos e encontros próprios. A wiki conecta as salas às missões e aos padrões de cada chefe.','dungeons'],
 ['Uma forja, muitas decisões','Armas definem sua forma de lutar; broches dão efeitos próprios e uma aura sutil. Conheça os materiais, requisitos e receitas de Bento, com o estado de cada sistema indicado.','itens'],
 ['Um lugar para voltar','O acampamento e a casa fazem parte da vida entre expedições. A casa começa vazia; na direção aprovada, móveis comprados com ouro aparecem nos lugares estabelecidos.','guias/casa'],
 ].map(([title,body,url])=><article key={title}><h3>{title}</h3><p>{body}</p><Link className="alvo-toque mt-2 inline-flex items-center" href={`${WIKI}/${url}`}>Consultar na wiki →</Link></article>)}</div><p className="mw-muted text-xs mt-4">Esta apresentação reúne experiência em desenvolvimento e direção aprovada. As fichas distinguem dados documentados de recursos planejados.</p></section>
 <section className="mw-section"><p className="mw-eyebrow">Conheça seu estilo</p><h2>A classe é sua. O nome também.</h2><div className="mw-cards">{entries.filter(e=>e.category==='classes').map(e=><Link className="mw-class" href={entryPath(e)} key={e.id}>{e.image?<Image src={e.image.src} alt="" width={160} height={160}/>:null}<strong>{e.title}</strong></Link>)}</div></section>
 <section className="mw-section"><p className="mw-eyebrow">Dentro do jogo</p><h2>Capturas do protótipo</h2><div className="mw-captures">{morvelio.galeria.map(c=><figure key={c.src}><Image src={c.src} alt={c.alt} width={c.largura} height={c.altura} sizes="(max-width:760px) 28vw, 400px"/><figcaption>{c.legenda}</figcaption></figure>)}</div></section>
 <section className="mw-section mw-atlas-teaser">{atlas.image?<Link href={entryPath(atlas)}><Image {...atlas.image} alt="Atlas ilustrado do mundo de Erdávia" sizes="(max-width:760px) 90vw, 700px"/></Link>:null}<div><p className="mw-eyebrow">O universo além da campanha</p><h2>Cinco reinos.<br/>Gerações de histórias.</h2><p className="mw-muted">O livro amplia Velidor para Erdávia: três reinos humanos, um reino anão e uma ilha élfica isolada. A saga atravessa reinados, paz e novas sombras. O atlas apresenta esse mundo literário e suas possibilidades futuras.</p><Link className="mw-button secondary" href={`${WIKI}/reinos`}>Explorar os cinco reinos →</Link></div></section>
 <section className="mw-section"><h2>Informações do projeto</h2><p className="mw-muted">{morvelio.aviso}</p><nav aria-label="Informações do Morvelio" className="mw-landing-links"><Link href={`${WIKI}/sobre`}>Sobre a wiki</Link><Link href="/morvelio/support">Suporte</Link><Link href="/morvelio/privacy">Privacidade</Link><Link href="/morvelio/terms">Termos</Link><Link href="/morvelio/delete-account">Excluir conta</Link></nav></section></div>;
}
