import type { ReactNode } from 'react';
import Image from 'next/image';
import Link from 'next/link';
import { notFound } from 'next/navigation';
import { AtlasViewer } from './AtlasViewer';
import { WIKI, ICON, categories, entries, edition, categoryName, entryPath, getEntry, listEntries, related, scoped, spoilerLevel, value, values, queryUrl, type Entry, type Query } from '@/content/morvelio/wiki/registry';
import './Wiki.css';

export function WikiShell({ children, current = '', level = 0 }: { children: ReactNode; current?: string; level?: number }) {
  const links = <ul><li><Link href={scoped(WIKI,level)} aria-current={current === 'inicio' ? 'page' : undefined}><span>⌂</span>Visão geral</Link></li>{categories.map(c=><li key={c.id}><Link href={scoped(`${WIKI}/${c.id}`,level)} aria-current={current===c.id?'page':undefined}><span aria-hidden="true">{c.symbol}</span>{c.title}</Link></li>)}<li><Link href={scoped(`${WIKI}/comparar`,level)}><span>⇄</span>Comparar equipamento</Link></li><li><Link href={`${WIKI}/atualizacoes`}><span>↻</span>Atualizações</Link></li><li><Link href={`${WIKI}/sobre`}><span>?</span>Sobre a wiki</Link></li></ul>;
  return <div className="mwiki" data-conduto-lado="direita"><header className="mw-top"><Link href={WIKI} aria-label="Início da Morvelio Wiki"><Image src={ICON} alt="" width={58} height={58} /></Link><div><strong>MORVELIO WIKI</strong><small>O arquivo de um mundo em construção</small></div><Link href="/projects/morvelio">Conhecer o jogo ↗</Link></header><div className="mw-layout"><aside className="mw-nav"><nav className="mw-desktop-nav" aria-label="Categorias da wiki"><p className="mw-eyebrow mb-3">Explorar o arquivo</p>{links}</nav><details className="mw-mobile-nav"><summary>Categorias e navegação</summary><nav aria-label="Categorias da wiki no celular">{links}</nav></details></aside><div className="mw-main" id="wiki-conteudo">{children}</div></div></div>;
}

export function Search({ q = '', level = 0 }: { q?: string; level?: number }) {
  return <form action={`${WIKI}/busca`} className="mw-search" role="search"><label className="sr-only" htmlFor="wiki-search">Buscar na wiki</label><input id="wiki-search" name="q" type="search" defaultValue={q} maxLength={160} placeholder="Itens, classes, missões, lugares…" />{level>0?<input type="hidden" name="spoilers" value={level}/>:null}<button type="submit">Buscar</button></form>;
}
function Spoilers({ path, query }: { path: string; query: Query }) {
  return <form action={path} className="mw-spoilers"><label htmlFor="spoilers">História visível</label><select id="spoilers" name="spoilers" defaultValue={spoilerLevel(query)}><option value="0">Sem spoilers</option><option value="1">Campanha e atividades finais</option><option value="2">Desfecho da campanha</option><option value="3">Saga completa</option></select>{Object.keys(query).filter(k=>k!=='spoilers'&&k!=='pagina').flatMap(k=>values(query,k).map((v,i)=><input type="hidden" key={`${k}-${i}`} name={k} value={v}/>))}<button type="submit">Aplicar</button></form>;
}
function Badges({ entry }: { entry: Entry }) { return <div className="mw-badges"><span className="mw-badge">{entry.kind || categoryName(entry.category)}</span><span className="mw-badge">{entry.scope}</span><span className={`mw-badge ${entry.status==='Planejado'?'planned':''}`}>{entry.status}</span>{entry.rarity?<span className="mw-badge">{entry.rarity}</span>:null}</div>; }
export function EntryTable({ list, level }: { list: Entry[]; level: number }) {
  return <div className="mw-table-wrap" tabIndex={0} role="region" aria-label="Tabela de fichas"><table className="mw-table"><thead><tr><th scope="col">Nome</th><th scope="col">Tipo</th><th scope="col">Classe / lugar</th><th scope="col">Estado</th></tr></thead><tbody>{list.map(e=><tr key={e.id}><td className="mw-name"><Link className="mw-row-title" href={scoped(entryPath(e),level)}>{e.image&&!e.image.src.includes('/maps/')?<Image src={e.image.src} alt="" width={40} height={40}/>:null}<span><strong>{e.title}</strong><small>{e.aliases.join(' · ')}</small></span></Link><p className="mw-row-desc">{e.summary}</p></td><td>{e.kind||categoryName(e.category)}{e.level!==null?<small className="block mw-muted">Nível {e.level}</small>:null}</td><td>{e.className||e.region||e.scope}</td><td><span className={`mw-badge ${e.status==='Planejado'?'planned':''}`}>{e.status}</span></td></tr>)}</tbody></table></div>;
}
export function WikiHome({ query }: { query: Query }) {
  const level=spoilerLevel(query);const atlas=getEntry('world.erdavia')!;
  return <WikiShell current="inicio" level={level}><div className="mw-hero"><div><p className="mw-eyebrow">Velidor é só o começo</p><h1>Prepare a aventura.<br/>Descubra o mundo.</h1><p className="mw-lead">De um broche na forja de Bento às casas reais de Erdávia. Encontre o que procura e siga os caminhos que conectam cada história.</p><Search level={level}/><div className="mw-quick"><Link href={`${WIKI}/guias/primeiros-passos`}>Primeiros passos ↗</Link><Link href={`${WIKI}/itens`}>Equipamento ↗</Link><Link href={`${WIKI}/missoes`}>Missões ↗</Link></div></div><Image src={ICON} alt="Morvelio observa Velidor; o Orbe ilumina sua bolsa" width={512} height={512} priority/></div>
    <div className="mw-statline"><span><strong>7</strong>classes</span><span><strong>{entries.filter(e=>e.category==='missoes').length}</strong>missões documentadas</span><span><strong>5</strong>reinos na saga</span><span><strong>{entries.length}</strong>fichas de consulta</span></div>
    <p className="mw-muted text-xs mt-4">Base documental · {edition}. Recursos planejados têm identificação própria; o atlas da saga não representa cinco reinos jogáveis no mobile.</p>
    <section className="mw-section"><p className="mw-eyebrow">Encontre seu caminho</p><h2>O que você quer descobrir?</h2><div className="mw-grid">{categories.filter(c=>!['mundo','reinos','cronicas','guias'].includes(c.id)).map(c=><Link className="mw-category" key={c.id} href={scoped(`${WIKI}/${c.id}`,level)}><span aria-hidden="true">{c.symbol}</span><strong>{c.title} →</strong><p>{c.description}</p></Link>)}</div></section>
    <section className="mw-section"><p className="mw-eyebrow">A classe é sua. O nome também.</p><h2>Sete maneiras de resistir</h2><div className="mw-cards">{entries.filter(e=>e.category==='classes').map(e=><Link className="mw-class" key={e.id} href={entryPath(e)}>{e.image?<Image src={e.image.src} alt="" width={160} height={160}/>:null}<strong>{e.title}</strong></Link>)}</div></section>
    <section className="mw-section mw-atlas-teaser"><Link href={entryPath(atlas)}>{atlas.image?<Image {...atlas.image} alt="Carta ilustrada de Erdávia" sizes="(max-width:760px) 90vw, 600px"/>:null}</Link><div><p className="mw-eyebrow">Além de Velidor · universo literário</p><h2>Um mar entre reinos.<br/>Um Orbe entre eras.</h2><p className="mw-muted">Velidor, Caldria, Durnagal, Sahram e Orissel. Explore as cartas, conheça as casas reais e acompanhe as histórias que atravessam gerações.</p><Link className="mw-button secondary" href={entryPath(atlas)}>Abrir o atlas →</Link></div></section>
    <section className="mw-section"><h2>Para a próxima expedição</h2><ul className="mw-related">{entries.filter(e=>e.category==='guias'&&e.spoiler<=level).map(e=><li key={e.id}><Link href={scoped(entryPath(e),level)}>{e.title} →</Link><small>{e.summary}</small></li>)}</ul></section>
  </WikiShell>;
}
export function WikiList({ category, query }: { category?: string; query: Query }) {
  if(category&&!categories.some(c=>c.id===category))notFound();
  const level=spoilerLevel(query);const path=category?`${WIKI}/${category}`:`${WIKI}/busca`;const result=listEntries(query,category);
  const options=(field: keyof Entry)=>[...new Set(result.base.map(e=>e[field]).filter((v):v is string=>typeof v==='string'&&v.length>0))].sort((a,b)=>a.localeCompare(b,'pt-BR'));
  const filters:[string,string,keyof Entry][]=[['Tipo','tipo','kind'],['Classe','classe','className'],['Região','regiao','region'],['Raridade','raridade','rarity'],['Estado','estado','status'],['Universo','escopo','scope']];
  return <WikiShell current={category ?? "busca"} level={level}><div className="mw-breadcrumbs"><Link href={WIKI}>Wiki</Link><span>/</span><span>{category?categoryName(category):'Busca'}</span></div><p className="mw-eyebrow">Banco de conhecimento</p><h1>{category?categoryName(category):'Encontre na wiki'}</h1><p className="mw-lead">{categories.find(c=>c.id===category)?.description??'Procure por nome, efeito, classe ou código de missão.'}</p><Spoilers path={path} query={query}/>
    <form action={path}><div className="mw-search"><label className="sr-only" htmlFor="list-search">Pesquisar fichas</label><input name="q" id="list-search" type="search" placeholder="Filtrar por nome, efeito ou missão…" defaultValue={value(query,'q')} maxLength={160}/><button>Pesquisar</button></div><input type="hidden" name="spoilers" value={level}/>
      <details className="mw-filters" open><summary>Filtros da consulta</summary><div className="mw-filter-grid">{!category?<label>Categoria<select name="categoria" defaultValue={value(query,'categoria')}><option value="">Todas</option>{categories.map(c=><option key={c.id} value={c.id}>{c.title}</option>)}</select></label>:null}{filters.filter(([, ,field])=>options(field).length>0).map(([label,key,field])=><fieldset key={key} className="mw-multi"><legend>{label}</legend><details open={values(query,key).length>0}><summary>{values(query,key).length ? `${values(query,key).length} selecionadas` : "Todas as opções"}</summary><div>{options(field).map(v=><label key={v}><input type="checkbox" name={key} value={v} defaultChecked={values(query,key).includes(v)}/><span>{v}</span></label>)}</div></details></fieldset>)}{result.base.some(e=>e.level!==null)?<><label>Nível mínimo documentado<input type="number" name="nivel" min="1" max="50" defaultValue={value(query,'nivel')}/></label><label>Nível máximo documentado<input type="number" name="ate" min="1" max="50" defaultValue={value(query,'ate')}/></label></>:null}<label>Ordenar<select name="ordem" defaultValue={value(query,'ordem')}><option value="">Relevância / nome</option><option value="nome">Nome A–Z</option><option value="nivel">Nível crescente</option></select></label></div><div className="mw-filter-actions"><button>Aplicar filtros</button><Link href={scoped(path,level)}>Limpar filtros</Link>{category==='itens'?<Link href={scoped(`${WIKI}/comparar`,level)}>Comparar equipamento →</Link>:null}</div></details>
    </form><p className="mw-muted text-sm mb-4" aria-live="polite">{result.total} {result.total===1?'ficha encontrada':'fichas encontradas'} · página {result.page} de {result.pages}{result.hidden>0?` · ${result.hidden} fichas protegidas por spoilers`:''}</p>
    {result.results.length?<EntryTable list={result.results} level={level}/>:<div className="mw-empty"><h2>Nenhuma ficha com esses filtros</h2><p className="mw-muted">Experimente outro nome ou remova um filtro. Valores ainda não documentados não entram no filtro de nível.</p><Link href={scoped(path,level)}>Limpar a consulta</Link></div>}
    <nav aria-label="Páginas de resultados" className="mw-pagination">{result.page>1?<Link href={queryUrl(path,query,{pagina:String(result.page-1)})}>← Anterior</Link>:<span/>}<span>{result.page} / {result.pages}</span>{result.page<result.pages?<Link href={queryUrl(path,query,{pagina:String(result.page+1)})}>Próxima →</Link>:<span/>}</nav>
  </WikiShell>;
}
export function WikiEntry({ entry, query }: { entry: Entry; query: Query }) {
  const level=spoilerLevel(query); const allowed=entry.spoiler<=level;const path=entryPath(entry);const sections=entry.sections.filter(s=>s.spoiler<=level);const connected=allowed?related(entry,level):[];
  return <WikiShell current={entry.category} level={level}><div className="mw-breadcrumbs"><Link href={scoped(WIKI,level)}>Wiki</Link><span>/</span><Link href={scoped(`${WIKI}/${entry.category}`,level)}>{categoryName(entry.category)}</Link><span>/</span><span>{allowed?entry.title:'Conteúdo protegido'}</span></div><Search level={level}/><Spoilers path={path} query={query}/>
    {!allowed?<div className="mw-notice"><p className="mw-eyebrow">Você escolhe quanto descobrir</p><h1>Esta ficha contém spoilers</h1><p>Ela revela {entry.spoiler===3?'acontecimentos posteriores da saga':entry.spoiler===2?'o desfecho da campanha':'etapas avançadas da campanha'}. O conteúdo e suas relações estão ocultos.</p><Link className="mw-button mt-5" href={scoped(path,entry.spoiler)}>Revelar esta parte da história</Link></div>:<>
    <div className="mw-detail-heading mt-7">{entry.image&&!entry.image.src.includes('/maps/')?<Image className="mw-portrait" src={entry.image.src} alt={entry.image.alt} width={100} height={100}/>:null}<div><p className="mw-eyebrow">{categoryName(entry.category)}</p><h1>{entry.title}</h1></div></div><Badges entry={entry}/><p className="mw-lead">{entry.summary}</p>
    {entry.status==='Planejado'?<p className="mw-notice">Direção de design documentada. Esta ficha não comprova que a peça ou receita já esteja disponível na versão distribuída do jogo.</p>:null}
    <div className="mw-detail"><div className="mw-body">{entry.image?.src.includes('/maps/')?<AtlasViewer image={entry.image}/>:null}{sections.map((s,i)=><section id={`secao-${i}`} key={`${s.title}-${i}`}><h2>{s.title}</h2>{s.paragraphs?.map((p,j)=><p key={j}>{p}</p>)}{s.rows&&s.headers?<div className="mw-table-wrap" tabIndex={0} role="region" aria-label={s.title}><table className="mw-table"><thead><tr>{s.headers.map(h=><th scope="col" key={h}>{h}</th>)}</tr></thead><tbody>{s.rows.map((r,j)=><tr key={j}>{r.map((v,k)=><td key={k}>{v}</td>)}</tr>)}</tbody></table></div>:null}</section>)}
      {entry.sections.some(s=>s.spoiler>level)?<p className="mw-notice">Há informações de história ocultas. Use “História visível” acima para revelar as etapas desejadas.</p>:null}
      {connected.length>0?<section><h2>Continue a pesquisa</h2><ul className="mw-related">{connected.map(r=><li key={r.entry.id}><small>{r.label}</small><Link href={scoped(entryPath(r.entry),level)}>{r.entry.title} →</Link></li>)}</ul></section>:null}
    </div><aside className="mw-facts"><h2>Ficha rápida</h2><dl>{entry.facts.map((f,i)=><div key={i}><dt>{f.label}</dt><dd>{f.value}</dd></div>)}</dl>{entry.category==='itens'&&['Arma','Broche'].includes(entry.kind)?<Link className="mw-button secondary mt-5" href={queryUrl(`${WIKI}/comparar`,{a:entry.slug,spoilers:String(level)},{})}>Comparar esta peça</Link>:null}<nav aria-label="Nesta ficha" className="mw-toc mt-6">{sections.map((s,i)=><a key={i} href={`#secao-${i}`}>{s.title}</a>)}</nav></aside></div>
    <footer className="mw-sources"><h2>Fontes e edição</h2><p>Dados da documentação de Morvelio. Valores de combate pertencem à edição consultada e podem mudar com o balanceamento.</p><ul>{entry.sources.map((s,i)=><li key={i}>{s.title} · {s.edition} · {s.locator}</li>)}</ul><Link href={`${WIKI}/sobre`}>Como esta wiki é mantida →</Link></footer>
    </>}
  </WikiShell>;
}
export function WikiCompare({ query }: { query: Query }) {
  const level=spoilerLevel(query);const choices=entries.filter(e=>e.category==='itens'&&['Arma','Broche'].includes(e.kind)&&e.spoiler<=level);
  const a=choices.find(e=>e.slug===value(query,'a'));const b=choices.find(e=>e.slug===value(query,'b'));
  const compatible=!!a&&!!b&&a.kind===b.kind&&(a.kind==='Broche'||a.className===b.className);
  const labels=[...new Set([...(a?.facts??[]),...(b?.facts??[])].map(f=>f.label))];
  return <WikiShell level={level}><p className="mw-eyebrow">Uma decisão, duas opções</p><h1>Comparar equipamento</h1><p className="mw-lead">Compare dois broches ou duas armas da mesma classe. Os efeitos são os da edição documental; não há cálculo inventado de DPS.</p><form action={`${WIKI}/comparar`}><input type="hidden" name="spoilers" value={level}/><div className="mw-compare">{(['a','b'] as const).map((key,i)=><label key={key}>Peça {i+1}<select name={key} defaultValue={value(query,key)} required><option value="">Escolha um equipamento</option>{choices.map(e=><option value={e.slug} key={e.id}>{e.title}</option>)}</select></label>)}</div><button>Comparar</button></form>
    {a&&b&&!compatible?<p className="mw-notice">Escolha peças do mesmo espaço. Para armas, use também a mesma classe.</p>:null}{compatible&&a&&b?<div className="mw-table-wrap mt-6"><table className="mw-table"><thead><tr><th scope="col">Característica</th>{[a,b].map((e,i)=><th key={i} scope="col"><Link href={entryPath(e)}>{e.title}</Link><span className="block mw-muted">{e.status}</span></th>)}</tr></thead><tbody>{labels.map(label=><tr key={label}><th scope="row">{label}</th>{[a,b].map((e,i)=><td key={i}>{e.facts.find(f=>f.label===label)?.value??'Não documentado'}</td>)}</tr>)}</tbody></table></div>:null}
  </WikiShell>;
}
export function WikiAbout({ updates = false }: { updates?: boolean }) {
  return <WikiShell current={updates?'atualizacoes':'sobre'}><p className="mw-eyebrow">Morvelio · Blajeen Labs</p><h1>{updates?'Atualizações da wiki':'Sobre este arquivo'}</h1>{updates?<><h2>Edição documental de {edition}</h2><ul className="mw-updates"><li>Fichas de classes, habilidades, talentos, itens, receitas, personagens, criaturas e missões.</li><li>Direção atual de broches, origem e nome do aventureiro reconciliada com os volumes de consulta.</li><li>Atlas de Erdávia e dos cinco reinos, com separação entre campanha e saga.</li><li>Busca por nome e código de missão; filtros, comparação e proteção de spoilers.</li></ul><p className="mw-notice">Este é o histórico da wiki. Não é uma nota de atualização do aplicativo.</p></>:<><p className="mw-lead">Uma wiki oficial de consulta para o universo de Morvelio, feita a partir dos oito volumes de documentação do jogo, do atlas e das diretrizes editoriais mais recentes.</p><section className="mw-section"><h2>O que significam os estados?</h2><p><strong>Documentado:</strong> descrito na edição citada; não é prova de que a versão pública já contenha o recurso.</p><p className="mt-3"><strong>Planejado:</strong> direção de design ou expansão ainda sem confirmação de implementação. Receitas e valores aparecem para consulta com essa identificação.</p><p className="mt-3"><strong>Mobile / Saga:</strong> o primeiro é o recorte do jogo; o segundo abrange os cinco reinos e outras eras. Conhecer um reino no atlas não libera viagem para ele no aplicativo.</p></section><section className="mw-section"><h2>Fontes e correções</h2><p>As fichas indicam volume, edição e localização da fonte. Diretrizes recentes de classes e broches prevalecem sobre termos antigos. Quando um valor não está definido, a wiki informa a ausência.</p><p className="mt-3">Dados são revisados antes de publicar. Os PDFs de produção, arquivos-fonte de assets e informações internas não são distribuídos por esta área.</p><Link href="/morvelio/support" className="mw-button secondary mt-5">Informar uma correção</Link></section><section className="mw-section"><h2>Você controla os spoilers</h2><p>Buscas e fichas começam sem desfechos. A opção “História visível” libera campanha, final ou saga completa. Conteúdo protegido não é enviado na página até você escolher revelá-lo. O link guarda essa escolha; ao compartilhá-lo, ela acompanha a URL.</p></section></>}</WikiShell>;
}
